import streamlit as st
import os

# --- CONFIG & STYLING ---
st.set_page_config(
    page_title="Google Photos Dashboard",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Minimal CSS to maintain premium dark theme without breaking image aspect ratios
st.markdown("""
<style>
    :root {
        --bg-color: #0f172a;
        --text-primary: #f8fafc;
    }
    .stApp {
        background-color: var(--bg-color);
        color: var(--text-primary);
        font-family: 'Inter', 'Roboto', sans-serif;
    }
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header {background: transparent !important;}
    
    /* Ensure images have a premium border but do NOT restrict max-height to avoid cropping text! */
    .stImage > img {
        border-radius: 8px;
        box-shadow: 0 4px 6px -1px rgba(0,0,0,0.5);
    }
</style>
""", unsafe_allow_html=True)

# --- INTERACTIVE SIDEBAR NAVIGATION ---
st.sidebar.title("🔍 Google Photos Dashboard")
st.sidebar.markdown("Click below to dynamically interact with the dashboard views.")

slide_mapping = {
    "1. Discovery Overview": "google_photos_retrieval_discovery_overview",
    "2. Research Dataset": "google_photos_research_dataset",
    "3. Search Behavior": "google_photos_search_behavior",
    "4. User Feedback": "google_photos_user_feedback",
    "5. Where Retrieval Breaks": "where_google_photos_retrieval_breaks",
    "6. Product Opportunities": "evidence_product_opportunities"
}

selected_view = st.sidebar.radio(
    "Interactive Menu:",
    list(slide_mapping.keys())
)

st.sidebar.markdown("---")
st.sidebar.info("This interactive dashboard natively displays the exact data and insights generated by the Stitch product intelligence engine. Zero mock data is used.")

# --- MAIN DASHBOARD FRAME ---
st.title(selected_view[3:]) # Remove the "1. " prefix for the main title

stitch_dir = "stitch_google_photos_retrieval_discovery_engine/stitch_google_photos_retrieval_discovery_engine"
folder = slide_mapping[selected_view]
img_path = os.path.join(stitch_dir, folder, "screen.png")

import base64

if os.path.exists(img_path):
    # Convert image to base64 so we can render it natively in HTML without Streamlit quirks
    with open(img_path, "rb") as image_file:
        encoded_string = base64.b64encode(image_file.read()).decode()
    
    # Render using pure HTML/CSS to guarantee 100% visibility and zero cropping
    html_code = f'''
    <div style="display: flex; justify-content: center; width: 100%;">
        <img src="data:image/png;base64,{encoded_string}" style="max-width: 100%; height: auto; border-radius: 8px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.5);">
    </div>
    '''
    st.markdown(html_code, unsafe_allow_html=True)
else:
    st.error(f"Image not found for {selected_view}.")
